// ParameterDescriptions - the plugin's whole knowledge of the FS1R's parameter map.
//
// Loaded from parameterDescriptions_fs1r.json (generated by tools/gen_parameters.py from the Data List
// tables). The plugin never reads engine internals: each description carries the sysex address it
// writes to and the engine echoes the change back.
#pragma once
#include <juce_core/juce_core.h>
#include <string>
#include <vector>

namespace fs1rplug {

struct ParamDesc {
    juce::String name;          // as shown, already unique inside its group
    juce::String group;         // Performance, Part, Voice, Op n, Op n Unvoiced, Effects, System
    juce::String description;
    juce::String unit;
    int addr[3] = {0, 0, 0};    // sysex parameter address, high / mid / low
    int min = 0, max = 127, def = 0;
    int shift = 0, width = 0;   // a field packed inside the byte; width 0 means the whole byte
    int displayOffset = 0;      // value + displayOffset is what the user reads
    bool bipolar = false, discrete = false, wide = false, partRelative = false;
    juce::StringArray values;   // value-to-text for discrete parameters

    juce::String uniqueId() const { return group + "/" + name; }
    juce::String textFor(int v) const {
        if (discrete && v >= 0 && v < values.size()) return values[v];
        juce::String t(v + displayOffset);
        if (bipolar && v + displayOffset > 0) t = "+" + t;
        return unit.isEmpty() ? t : t + " " + unit;
    }
};

// Parses the JSON. Returns false and leaves the list empty if the document is not the expected shape.
bool loadParameterDescriptions(const void* jsonData, int numBytes, std::vector<ParamDesc>& out);

}  // namespace fs1rplug
