# Pull the CPU-side conversion tables out of the v1.20 EPROM image into src/fs1r/firmware/tables.h.
#   python tools/extract_tables.py
import struct
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
rom = (ROOT.parent / "FS1R_DISASM/roms/fs1r_v120_eprom_cpuview.bin").read_bytes()
def W(a, n, s=False): return struct.unpack(">%d%s" % (n, "h" if s else "H"), rom[a - 0x200000:a - 0x200000 + 2 * n])
def B(a, n, s=False): return struct.unpack(">%d%s" % (n, "b" if s else "B"), rom[a - 0x200000:a - 0x200000 + n])
tables = [  # name, ctype, values, comment
 ("LEVTAB", "unsigned char", B(0x35B4A8, 100), "level 0..99 -> attenuation, 0.75 dB per step (DX7 curve)"),
 ("PEGLVL", "unsigned short", W(0x35B50C, 101), "pitch EG level 0..100 -> 0..256, 128 = centre; word = (v-128)<<7"),
 ("PEGTIME", "unsigned short", W(0x35B5D6, 100), "pitch EG / portamento time 0..99 -> level units per tick"),
 ("FEGLVL", "unsigned char", B(0x35B2E0, 101), "frequency EG level 0..100 -> 0..255, 128 = centre (registers 0x60/0x68, image +0x98/+0xA0). MEASURED against the voice images in FS1R.unlock/captures/2026-09-19"),
 ("VELW", "unsigned char", [x & 0xFF for x in W(0x35BA1E, 128)], "velocity 0..127 -> attenuation, 0.375 dB units (255 at 0)"),
 ("VELCURVE", "unsigned char", B(0x35B99E, 128), "velocity remap used for the Fseq level velocity"),
 ("EGBIAS", "unsigned char", [min(255, x) for x in W(0x35CD24, 256)], "controller 0..255 -> attenuation for EG bias and LFO AM"),
 ("KSEXP", "unsigned char", B(0x35C3EB, 40), "level key scaling, exponential curves, per 3-semitone group"),
 ("KSLIN", "unsigned char", B(0x35C413, 40), "level key scaling, linear curves"),
 ("KEYFACT", "unsigned char", B(0x35C43B, 128), "note -> key factor (>>2 for PEG rate scaling, >>2 then -3 for key groups)"),
 ("NOTETAB", "unsigned short", W(0x35B346, 128), "note -> pitch word (1024 per octave, +0x1243 elsewhere)"),
 ("COARSE", "short", W(0x35BC32, 32, True), "ratio coarse 0..31 -> 1024*log2(ratio)"),
 ("FINE", "short", W(0x35BC72, 100, True), "ratio fine 0..99 -> 1024*log2(1+f/100)"),
 ("TRANS", "short", W(0x35B446, 49, True), "transpose 0..48 (-24..+24) -> pitch word offset"),
 ("BENDTAB", "unsigned short", W(0x35BBD0, 49), "semitones 0..48 -> pitch word units"),
 ("SINE64", "unsigned char", [x & 0xFF for x in W(0x35CC94, 64)], "LFO sine quarter wave"),
 ("SHTAB", "signed char", B(0x35CF24, 2048, True), "LFO sample and hold random walk table"),
 ("FVSTAB", "unsigned char", B(0x35C4BC, 9), "frequency velocity sensitivity multipliers"),
 ("BWBIAS", "signed char", B(0x35C533, 16, True), "bandwidth bias -7..+7 -> controller multiplier"),
 ("FRMDET", "signed char", B(0x35BE06, 512, True), "formant detune: [detune band 0..15][pitch band 0..31]"),
 ("VNBAL", "unsigned char", [x & 0xFF for x in B(0x35BB1E, 128, True)], "part level index -> attenuation for the voiced/unvoiced level bytes"),
 ("PEGVEL", "unsigned char", B(0x35C870, 8), "pitch EG velocity sensitivity 0..7 -> multiplier (computed then overridden by the firmware)"),
 ("PANL", "unsigned char", B(0x35C0EB, 128), "pan index 0..127 (pan byte >> 1) -> left attenuation, 0.375 dB units (register 0x22C/0x22E)"),
 ("PANR", "unsigned char", B(0x35C16B, 128), "pan index -> right attenuation (register 0x22D/0x22F); PANR[i] == PANL[127-i]"),
 ("SENDTAB", "unsigned char", B(0x35C006, 128), "send level 0..127 -> attenuation"),
 ("VELCURVES", "unsigned char", B(0x35B71E, 5 * 128), "system velocity curves [curve][velocity]"),
 ("FEGRATE", "unsigned short", W(0x374F4E, 100), "filter EG time 0..99 -> VOP3-1 rate word, register 0x2B (FUN_0000D050, FUN_0000CB6C, FUN_0000D7B0); 0xFF past the end is the hold"),
 ("FSEQDLY", "unsigned short", W(0x35BD3E, 100), "Fseq start delay 0..99 -> frames of the 7000-count CMT1 period (FUN_0001A560)"),
 ("DX7MAP", "unsigned short", W(0x389F8C, 32 * 33), "DX7 -> FS1R conversion rows (FUN_00035918/E96): [alg][33]: 0..15 connection words with the carrier"
  " correction in t1 bits 3-6, 16 the FS1R algorithm, 17..22 +2 on the output level for DX ops 6..1, 23..24 unknown,"
  " 25..30 the FS1R operator each DX op 6..1 lands on, 31..32 unknown"),
 ("DX7RATE_A", "signed char", B(0x38A84C, 100, True), "DX7 -> FS1R attack rate correction by rate"),
 ("DX7RATE_B", "signed char", B(0x38A8B0, 100, True), "DX7 -> FS1R decay/release rate correction by rate"),
 ("DX7CTRL", "unsigned short", W(0x38A7CC, 64), "DX7 -> FS1R: formant and FM control destination operator per DX algorithm, pairs"),
 ("DX7OPTEMPLATE", "unsigned char", B(0x38A914, 35), "DX7 -> FS1R: the voiced operator block of an unused slot (FUN_00035E96)"),
 ("DX7UOP", "unsigned char", B(0x38A937, 216), "DX7 -> FS1R: the unvoiced operator block per slot, 8 x 27 (FUN_00035E96)"),
 ("LFO2SPD", "unsigned short", W(0x374A04, 128), "LFO2 speed 0..127 -> VOP3-1 phase increment (FUN_0000C130)"),
]
out = ["// Generated by tools/extract_tables.py from the FS1R v1.20 EPROM. Do not edit.", "#pragma once"]
for name, ct, vals, cm in tables:
    out.append(f"// {cm}")
    rows = [", ".join(str(v) for v in vals[i:i + 16]) for i in range(0, len(vals), 16)]
    out.append(f"static const {ct} {name}[{len(vals)}] = {{\n    " + ",\n    ".join(rows) + "\n};")
(ROOT / "src/fs1r/firmware/tables.h").write_text("\n".join(out) + "\n")
print("wrote", len(tables), "tables")
