#!/usr/bin/env python3
"""Pull VOP3-1's microcode out of the FS1R v1.20 EPROM.

    python tools/extract_vop3.py

Writes docs/vop3_microcode.md (the boot sequence, the program listing and the coefficient tables, each
word labelled with the chip register it is written to) and docs/vop3/*.bin (the same data raw, for
anyone who wants to run a disassembler at it).

This is the 0x800200 upload, which the CS2 decode puts on VOP3-1, the per-voice filter (docs/research.md
section 8). VOP3-2's effect microcode is a separate pair of images at 0x372204 and 0x373604 that
FUN_0003C9C4 uploads through FUN_00039648, and it is not extracted yet.

Reference material only. Nothing in the engine or the plugin depends on it: the filter and the effects
shipped in the engine are models, because the VOP3 instruction set is not known. Decoding it is what
turns these bytes into a bit-exact filter.

Everything below is read from the firmware, not guessed:
  FUN_0000B5E2(reg, value)   writes 0x800200 + reg * 2, so register N lives at that address
  FUN_0000BC8C               the boot upload, which is where all of these addresses come from
  FUN_0000B600               patches program steps when a filter channel's type changes (FUN_0000D050)
"""
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROM = ROOT.parent / "FS1R_DISASM/roms/fs1r_v120_eprom_cpuview.bin"
OUT = ROOT / "docs"
BIN = OUT / "vop3"

BASE = 0x200000            # the EPROM sits at 0x200000 in the CPU map; file offset = address - BASE


def rd(rom, addr, n):
    return rom[addr - BASE: addr - BASE + n]


def words(rom, addr, n):
    return struct.unpack(">%dH" % n, rd(rom, addr, 2 * n))


def main():
    if not ROM.exists():
        raise SystemExit("EPROM image not found: %s" % ROM)
    rom = ROM.read_bytes()
    BIN.mkdir(parents=True, exist_ok=True)

    # 512 steps, five 16-bit words each, interleaved so word k of step n is at base + n*10 + k*2.
    # The upload writes word 0 to register 10 and counts down, so word k goes to register 10 - k.
    prog = {0: 0x375E1A, 1: 0x37721A}
    coef = {0: 0x37541A, 1: 0x37581A}
    steps = 512
    progWords = {v: words(rom, a, steps * 5) for v, a in prog.items()}
    coefWords = {v: words(rom, a, steps) for v, a in coef.items()}
    addrList = words(rom, 0x37501A, steps)          # written to register 0 before each coefficient
    byteTab = list(rd(rom, 0x375C1A, steps))        # written to register 0xC
    busVals = list(rd(rom, 0x37861A, 15))           # written to register 0x16, one per bus
    typeBlock = list(rd(rom, 0x374F2E, 16))         # filter channel -> program block, FUN_0000D050
    patchTab = list(rd(rom, 0x378629, 0x13))        # the per-type patch table STATUS.md names

    for v, w in progWords.items():
        (BIN / f"program_{v}.bin").write_bytes(struct.pack(">%dH" % len(w), *w))
    for v, w in coefWords.items():
        (BIN / f"coefficients_{v}.bin").write_bytes(struct.pack(">%dH" % len(w), *w))
    (BIN / "step_addresses.bin").write_bytes(struct.pack(">%dH" % len(addrList), *addrList))
    (BIN / "byte_table.bin").write_bytes(bytes(byteTab))

    md = []
    w = md.append
    w("# YSS236 (VOP3-1) microcode, FS1R v1.20 EPROM")
    w("")
    w("Generated by `tools/extract_vop3.py`. **Reference material only.** The filter and the effects the")
    w("emulator ships are models, because nobody has decoded this instruction set. The YSS236 is Yamaha's")
    w("VOP3, the same programmable DSP that is the synthesis engine of the AN1x, the AN200 and the")
    w("PLG150-AN and the vocal harmony processor of the PSR-9000, so a decode would reach well past this")
    w("one machine. No public description of the encoding exists.")
    w("")
    w("**This is VOP3-1's program, the per-voice filter, not the effects.** The FS1R has two VOP3s with a")
    w("register window each on CS2, decoded on A8 and A9: VOP3-1 at 0x800200 and VOP3-2 at 0x800000")
    w("(`docs/research.md` section 8). The upload below is the 0x800200 one. VOP3-2's effect microcode is")
    w("the pair of images at EPROM 0x372204 and 0x373604 that `FUN_0003C9C4` uploads through")
    w("`FUN_00039648`, and it has not been extracted.")
    w("")
    w("The chip's pinout is in `docs/vop3_pinout.md`, out of the AN200 service manual: 128 CPU registers,")
    w("8 serial audio inputs and 8 outputs, and a bank of external DRAM per chip. IC31, the FS1R's VOP3-1,")
    w("has nothing on those memory pins, which is why it cannot be the chip running the reverb.")
    w("")
    w("## Bus and boot sequence (FUN_0000BC8C)")
    w("")
    w("`FUN_0000B5E2(reg, value)` writes `0x800200 + reg * 2`, a 16-bit register block; status is at")
    w("0x800242. Register 0 selects an address, bit 15 of it selecting a second address space. The boot")
    w("upload runs in this order:")
    w("")
    w("| step | register | source | count |")
    w("|---|---|---|---|")
    w("| reset | 1 | - | - |")
    w("| mode | 5 | constant 0x1004 | - |")
    w("| per-bus levels | 0x16 (address = bus + 1 in reg 0) | 0x37861A | 15 bytes |")
    w("| per-bus | 0x28 | constant 0x15 | 15 |")
    w("| per-bus | 0x29 | constant 0x15 | 15 |")
    w("| per-bus | 0x2A | constant 0 | 15 |")
    w("| per-bus | (image 0x1000) | constant 0x1000 | 15 words |")
    w("| byte table | 0xC, address from 0x37501A \\| 0x8000 | 0x375C1A | 512 bytes |")
    w("| program | 10, 9, 8, 7, 6 per step | 0x375E1A (alt 0x37721A) | 512 x 5 words |")
    w("| coefficients | 0xB, address from 0x37501A | 0x37541A (alt 0x37581A) | 512 words |")
    w("| finish | 0x16 address 0, value 0x17; then 0x17 = 0 | - | - |")
    w("")
    w("The boot argument picks one of two variants, and it is a literal at both call sites: FUN_0000B010")
    w("passes 0 on the normal boot, FUN_0000B0E2 passes 1 from FUN_003C2038, the diagnostic entry. So the")
    w("two are the ordinary and the test configuration of one chip, not one program per chip.")
    w("")
    w("A filter type change (FUN_0000D050) does not re-upload: it mutes the channel's block, patches")
    w("program steps through FUN_0000B600 from a table indexed by type, and unmutes.")
    w("")
    w("## Filter channel to program block (0x374F2E)")
    w("")
    w("One byte per filter channel, 0 to 15, naming the program block FUN_0000D050 patches. It is a")
    w("rotation, channel n to block n + 2, which is what identified this block as the filter's:")
    w("")
    w("```")
    for i in range(0, len(typeBlock), 16):
        w("%02X: %s" % (i, " ".join("%02X" % b for b in typeBlock[i:i + 16])))
    w("```")
    w("")
    w("## Per-type patch table (0x378629)")
    w("")
    w("```")
    w(" ".join("%02X" % b for b in patchTab))
    w("```")
    w("")
    w("## Per-bus levels (0x37861A, register 0x16)")
    w("")
    w("```")
    w(" ".join("%02X" % b for b in busVals))
    w("```")
    w("")
    w("## Program, variant 0 (0x375E1A)")
    w("")
    w("Each row is one program step: the five words in the order they are written, to registers 10, 9, 8,")
    w("7 and 6. The word at file offset `step * 10 + k * 2` goes to register `10 - k`.")
    w("")
    w("| step | addr | r10 | r9 | r8 | r7 | r6 | coef (r0xB) | byte (r0xC) |")
    w("|---|---|---|---|---|---|---|---|---|")
    for n in range(steps):
        row = progWords[0][n * 5:(n + 1) * 5]
        w("| %3d | %04X | %s | %04X | %02X |" % (
            n, addrList[n], " | ".join("%04X" % x for x in row), coefWords[0][n], byteTab[n]))
    w("")
    progDiff = sum(1 for n in range(steps)
                   if progWords[0][n * 5:(n + 1) * 5] != progWords[1][n * 5:(n + 1) * 5])
    coefDiff = sum(1 for n in range(steps) if coefWords[0][n] != coefWords[1][n])
    nonZero = [n for n in range(steps) if any(progWords[1][n * 5:(n + 1) * 5]) or coefWords[1][n]]
    w("## Program, variant 1 (0x37721A, coefficients 0x37581A)")
    w("")
    w("Variant 1 is not a second full program: %d of its %d steps are entirely zero. Only the %d steps"
      % (steps - len(nonZero), steps, len(nonZero)))
    w("with anything in them are listed. It differs from variant 0 in %d program steps and %d"
      % (progDiff, coefDiff))
    w("coefficients, so the diagnostic configuration is a stripped program rather than an alternative set")
    w("of algorithms.")
    w("")
    w("| step | r10 | r9 | r8 | r7 | r6 | coef |")
    w("|---|---|---|---|---|---|---|")
    for n in nonZero:
        w("| %3d | %s | %04X |" % (n, " | ".join("%04X" % x for x in progWords[1][n * 5:(n + 1) * 5]),
                                   coefWords[1][n]))
    w("")
    diff = progDiff
    (OUT / "vop3_microcode.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print("wrote %s (%d steps, %d differing in variant 1)" % (OUT / "vop3_microcode.md", steps, diff))
    print("wrote raw dumps to %s" % BIN)


if __name__ == "__main__":
    main()
