#!/usr/bin/env python3
"""Pull VOP3-2's microcode out of the FS1R v1.20 EPROM.

    python tools/extract_vop3_2.py

Writes docs/vop3_2_microcode.md (the boot init and the two effect program listings, each word labelled
with the chip register it is written to) and docs/vop3_2/*.bin (the same data raw).

This is the 0x800000 upload, which the CS2 decode puts on VOP3-2, the effects chip (docs/research.md
section 8). VOP3-1's filter program is the separate extraction in `tools/extract_vop3.py`.

Reference material only. Nothing in the engine or the plugin depends on it: the effects shipped in the
engine are models, because the VOP3 instruction set is not known. Unlike VOP3-1, this chip has its
external DRAM fitted (the reverb needs it), so this program is what a decode turns into bit-exact
effects.

Everything below is read from the firmware, not guessed:
  FUN_00039648(reg, value)   writes 0x800000 + reg * 2, so register N lives at that address
  FUN_0003A064               the boot init
  FUN_0003C9C4(image)        the 512-step upload, image 0 from 0x373604 (normal) or 1 from 0x372204
  FUN_00039652 / FUN_000397F4  the coefficient-address (reg 0xB) and DRAM-address (0xD/0xE) writes at
                             the end of the upload, out of RAM tables the parameter path fills
"""
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROM = ROOT.parent / "FS1R_DISASM/roms/fs1r_v120_eprom_cpuview.bin"
OUT = ROOT / "docs"
BIN = OUT / "vop3_2"

BASE = 0x200000            # the EPROM sits at 0x200000 in the CPU map; file offset = address - BASE


def rd(rom, addr, n):
    return rom[addr - BASE: addr - BASE + n]


def words(rom, addr, n):
    return struct.unpack(">%dH" % n, rd(rom, addr, 2 * n))


def main():
    if not ROM.exists():
        raise SystemExit("EPROM image not found: %s" % ROM)
    rom = ROM.read_bytes()
    BIN.mkdir(parents=True, exist_ok=True)

    steps = 512
    # FUN_0003C9C4 loops the five words OUTER and the 512 steps INNER: word k of step n is at
    # imagebase + k*0x400 + n*2, written to register 10 - k. (VOP3-1's images interleave the other
    # way, step outer / word inner; the two chips' uploads are not the same walk.)
    prog_addr = {0: 0x373604, 1: 0x372204}
    for v, base in prog_addr.items():
        rows = [words(rom, base + k * 0x400 + n * 2, 1)[0]
                for n in range(steps) for k in range(5)]
        (BIN / f"program_{v}.bin").write_bytes(struct.pack(">%dH" % len(rows), *rows))

    # The RAM-side tables the upload finishes with: register 0xB's coefficient addresses out of
    # DAT_0106842c (populated from EPROM as the parameter path runs) and the DRAM address pairs out
    # of DAT_0106882c. The boot-time contents behind them: the per-bus level table at 0x37101A,
    # copied to DAT_01068cdc by FUN_0003A064, and the selector map at 0x3720A4.
    busVals = list(rd(rom, 0x37101A, 15))
    selMap = list(rd(rom, 0x3720A4, 8))
    initTail = words(rom, 0x3721FC, 2)          # thunk_FUN_00039652(2, &DAT_003721fc)
    dramSel = words(rom, 0x372200, 4)           # FUN_000397f4(4, &DAT_00372200)

    md = []
    w = md.append
    w("# YSS236 (VOP3-2) microcode, FS1R v1.20 EPROM")
    w("")
    w("Generated by `tools/extract_vop3_2.py`. **Reference material only.** The effects the emulator")
    w("ships are models, because nobody has decoded this instruction set. This is the effects chip's")
    w("program — the half of the VOP3 microcode nobody had looked at. VOP3-1's filter program is in")
    w("`docs/vop3_microcode.md`. The chip's pinout is in `docs/vop3_pinout.md`: unlike the filter")
    w("chip, this one has its external DRAM fitted, so a program here can be a reverb.")
    w("")
    w("## Bus and boot (FUN_0003A064)")
    w("")
    w("`FUN_00039648(reg, value)` writes `0x800000 + reg * 2`, a 16-bit register block. The boot init")
    w("writes register 1 (reset), register 5 = 0x1FF4, then fifteen per-bus levels out of EPROM")
    w("0x37101A into register 0x16 addressed per bus (bus + 1 selected through register 0), registers")
    w("0x28/0x29 held at 0x15 for the 15 buses, register 0x2A at 0, and finishes with register 1 = 0")
    w("and `FUN_0003A140(5, 1)`. The per-bus layout matches VOP3-1's boot for the same registers.")
    w("")
    w("Per-bus levels, 0x37101A -> register 0x16:")
    w("")
    w("```")
    w(" ".join("%02X" % b for b in busVals))
    w("```")
    w("")
    w("## The upload (FUN_0003C9C4)")
    w("")
    w("512 steps of five 16-bit words each. The walk is word-major: word k of step n sits at")
    w("`base + k*0x400 + n*2` and goes to register 10 - k (so the five words of a step land on")
    w("registers 10, 9, 8, 7 and 6, as on VOP3-1). Before each pass it writes register 0 with")
    w("0x8000. Image 0 at 0x373604 is uploaded on the normal boot; image 1 at 0x372204 from the")
    w("diagnostic entry, alongside VOP3-1's variant 1.")
    w("")
    w("## Program, image 0 (0x373604) -- the effects")
    w("")
    w("| step | r10 | r9 | r8 | r7 | r6 |")
    w("|---|---|---|---|---|---|")
    progRows = {v: [[words(rom, base + k * 0x400 + n * 2, 1)[0] for k in range(5)]
                    for n in range(steps)] for v, base in prog_addr.items()}
    for n in range(steps):
        w("| %3d | %s |" % (n, " | ".join("%04X" % x for x in progRows[0][n])))
    w("")
    nz1 = [n for n in range(steps) if any(progRows[1][n])]
    diff = sum(1 for n in range(steps) if progRows[1][n] != progRows[0][n])
    w("## Program, image 1 (0x372204)")
    w("")
    w("Image 1 differs from image 0 in %d of its %d steps, and %d steps are entirely zero. The"
      % (diff, steps, steps - len(nz1)))
    w("non-zero steps:")
    w("")
    w("| step | r10 | r9 | r8 | r7 | r6 |")
    w("|---|---|---|---|---|---|")
    for n in nz1:
        w("| %3d | %s |" % (n, " | ".join("%04X" % x for x in progRows[1][n])))
    w("")
    w("## The RAM-side finish")
    w("")
    w("After the 512 steps the upload writes two coefficient addresses through `FUN_00039652(2,`")
    w("`0x3721FC)` — register 0xB gets a per-slot word out of `DAT_0106842c` — and four DRAM")
    w("addresses through `FUN_000397f4(4, 0x372200)`, which splits `DAT_0106882c[sel] + offset`")
    w("into register 0xD (high, >> 9) and register 0xE (low, & 0x1FF), the offset picked by the")
    w("selector map at 0x3720A4 (%s). Those RAM tables are"
      % " ".join("%02X" % b for b in selMap))
    w("populated as the parameter path runs, so the program's working data is effect-dependent.")
    w("The two address words at 0x3721FC are 0x%04X, 0x%04X and the four selectors at 0x372200"
      % initTail)
    w("are %s." % ", ".join("0x%04X" % x for x in dramSel))
    w("")
    (OUT / "vop3_2_microcode.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print("wrote %s (%d steps; image 1 differs in %d)" % (OUT / "vop3_2_microcode.md", steps, diff))
    print("wrote raw dumps to %s" % BIN)


if __name__ == "__main__":
    main()
